name: GitHub CLI test

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.repository }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: package.json
      - run: gh release list
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
