name: GitHub Cli test

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo $OWNER
      - run: echo $REPO
      - run: gh api /repos/$OWNER/$REPO/releases
