name: Source Code Check

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run type-check
      - run: npm run lint

  note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: gh release view 0.6.1 --json body --jq '.body' > release-note.md
      - run: echo "ELECTRON_VER=$(npx electron -v)" >> $GITHUB_ENV
      - run: curl -s https://raw.githubusercontent.com/electron/electron/${{ env.ELECTRON_VER }}/DEPS > DEPS
      - run: node ./scripts/electron-ver.js >> release-note.md
      - run: cat release-note.md
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
